# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='planner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='members.Person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='secretary',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='members.Person'),
        ),
    ]
