# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutes',
            options={'permissions': [('approve', 'Can approve minutes')], 'verbose_name_plural': 'Minutes'},
        ),
    ]
