# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20160310_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='meetings.Meeting'),
        ),
    ]
