# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_minutes_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='original_name',
            field=models.TextField(),
        ),
    ]
