# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20160316_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutes',
            name='original_name',
        ),
    ]
