# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_remove_minutes_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='original_name',
            field=models.TextField(default='blaat.txt'),
            preserve_default=False,
        ),
    ]
