# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_minutes_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 16, 13, 17, 3, 7207, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
