# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_minutes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='begin_time',
            field=models.DateTimeField(verbose_name='Begin Date & Time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Date & Time'),
        ),
    ]
