# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_auto_20160405_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='planner',
        ),
    ]
