# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_remove_meeting_planner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutes',
            options={'permissions': [('approve', 'Can approve minutes')], 'verbose_name_plural': 'minutes'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='begin_time',
            field=models.DateTimeField(verbose_name='begin date & time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(verbose_name='end date & time'),
        ),
    ]
