# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Minutes',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField()),
                ('is_secretary', models.BooleanField()),
                ('is_planner', models.BooleanField()),
                ('organization', models.ManyToManyField(to='sokolov.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='minutes',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sokolov.User'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokolov.Meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokolov.Organization'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokolov.User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokolov.Meeting'),
        ),
    ]
