# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 20:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'person',
                'permissions': (('admin', 'Can do anything'), ('plan', 'Can schedule and change meetings'), ('take_minutes', 'Can upload minutes'), ('approve_minutes', 'Can approve minutes')),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='planner',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Organization'),
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Minutes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.ManyToManyField(blank=True, to='members.Organization'),
        ),
    ]
