# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_organization_parent_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='members.User'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='members.User'),
        ),
    ]
