# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160217_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Organization'),
        ),
    ]
