# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160218_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('admin', 'Can change user groups and change group permissions')], 'verbose_name': 'person'},
        ),
    ]
