# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160310_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizations',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='organization',
            new_name='organizations',
        ),
    ]
