# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20160318_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name': 'Preferences', 'verbose_name_plural': 'Preferences'},
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='overview',
        ),
        migrations.AddField(
            model_name='preferences',
            name='overview',
            field=models.ManyToManyField(blank=True, related_name='_preferences_overview_+', to='members.Organization'),
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='reminder',
        ),
        migrations.AddField(
            model_name='preferences',
            name='reminder',
            field=models.ManyToManyField(blank=True, related_name='_preferences_reminder_+', to='members.Organization'),
        ),
    ]
