# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20160215_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person'},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.AddField(
            model_name='minutes',
            name='file',
            field=models.FileField(default=None, upload_to='minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='begin_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ManyToManyField(blank=True, to='members.Organization'),
        ),
    ]
