# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160318_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='overview',
            field=models.ManyToManyField(blank=True, related_name='pref_overview', to='members.Organization'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='reminder',
            field=models.ManyToManyField(blank=True, related_name='pref_reminder', to='members.Organization'),
        ),
    ]
