# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160215_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('admin', 'Can do anything'), ('plan', 'Can schedule and change meetings'), ('take_minutes', 'Can upload minutes'), ('approve_minutes', 'Can approve minutes')), 'verbose_name': 'person'},
        ),
    ]
