# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20160215_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='planner',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='meeting',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Minutes',
        ),
    ]
