# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20160318_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='agenda_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferences',
            name='agenda_secretary',
            field=models.BooleanField(default=True),
        ),
    ]
