# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20160321_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='agenda_token',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='agenda_organization',
            field=models.BooleanField(default=False, verbose_name='Include meetings in your agenda which belong to your organizations'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='agenda_secretary',
            field=models.BooleanField(default=True, verbose_name='Include meetings in your agenda of which you are the secretary'),
        ),
    ]
