# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20160321_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='zoom_in',
            field=models.BooleanField(default=False, verbose_name='Always zoom in the page'),
        ),
    ]
