# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_preferences_zoom_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='overview_student',
            field=models.ManyToManyField(blank=True, related_name='student_pref_overview', to='members.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, help_text='The organization to which this organization belongs. For example, Technical Computer Science might belong to an organization called EWI.', null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='The student number or employee number of the user, for example s1234567 or m1234567', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
