# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_preferences_confirmation_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('list_organizations', 'Can list organizations')], 'verbose_name': 'organization'},
        ),
        migrations.AlterField(
            model_name='preferences',
            name='confirmation_student',
            field=models.BooleanField(default=False, verbose_name='Receive confirmation mail when adding yourself to a meeting'),
        ),
    ]
