# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20160401_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
