# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_person_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='overview_student',
            field=models.ManyToManyField(blank=True, related_name='student_pref_overview', to='members.Organization', verbose_name='overview secretary'),
        ),
    ]
