# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20160407_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='confirmation_student',
            new_name='confirmation_secretary',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='overview_student',
            new_name='overview_secretary',
        ),
        migrations.AlterField(
            model_name='preferences',
            name='agenda_organization',
            field=models.BooleanField(default=False, verbose_name='Include meetings in your calendar which belong to your organizations'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='agenda_secretary',
            field=models.BooleanField(default=True, verbose_name='Include meetings in your calendar of which you are the secretary'),
        ),
    ]
