# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20160408_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='agenda_token',
            new_name='calendar_token',
        ),
    ]
