# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20160408_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='agenda_organization',
            new_name='calendar_organization',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='agenda_secretary',
            new_name='calendar_secretary',
        ),
    ]
